### ISSUE TITLE
404 from CentOS 7.2 while trying to download Java

### ISSUE THREAD

**Issue by dylan-colaco** [dhoer/chef-java_se#26]
Getting a 404 for while running this recipe today. Running on CentOS 7.2.
The same recipe worked a few weeks ago. No attributes overwritten.

The chef error is:
ERROR: ruby_block[fetch http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz] (java_se::_linux_install line 66) had an error: ArgumentError: too many download failures from http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz

**Comment by dylan-colaco** [comment]
Fixed now. Probably a network issue

**Comment by philipthomasme** [comment]
I encounter the exact same issue but rather than having it fixed by itself, the error still occurs.
For me it seems like Oracle changed the way they check the permission to download their files and probably implemented a cookie barrier that prevents direct downloads.
It would be appreciated if somebody could double-check this.
